pipeline:
  name: This is github test
  identifier: This_is_github_test
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1734945152337
        repoName: RohitDarekar816/pipeline
        build: <+input>
  stages:
    - stage:
        name: Github build
        identifier: Github_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Python
                    command: print('Hello World')
    - stage:
        name: Login SSH
        identifier: Login_SSH
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: SSH Login
                  identifier: Ping_IP
                  spec:
                    shell: Sh
                    command: |-
                      sudo shh root@147.182.192.109
                      iamindian@1Iamindian
